spring:
  application:
    name: auth-service
  config:
    import: "optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}"
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        instanceId: ${spring.application.name}:${random.value}
        healthCheckPath: /actuator/health
        healthCheckInterval: 15s
        register: true
        prefer-ip-address: true

server:
  port: 9000

management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info
  endpoint:
    health:
      show-details: always
jwt:
  secret: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
  access-token:
    expiration: 900 # 15 minutes
  refresh-token:
    expiration: 604800 # 7 days
  id-token:
    expiration: 3600 # 1 hour
